### ISSUE TITLE
Chunked encoding does not require a persistent connection

### ISSUE THREAD

**Issue by darrelmiller** [mspnp/azure-guidance#10]
"web API can send the reply back in piecemeal chunks over a persistent HTTP connection"
https://github.com/mspnp/azure-guidance/blob/master/API-Implementation.md#considerations-for-handling-large-requests-and-responses

A request can include the header Connection: close and still do chunked encoding.  The connection will remain open until the final chunk has been sent.  Persistent connections are only required for sending multiple requests over the same connection.

**Comment by JohnPWSharp** [comment]
I have removed the reference to persistent connections.
