### ISSUE TITLE
Section on "Enable Continue status" should either be expanded or removed

### ISSUE THREAD

**Issue by darrelmiller** [mspnp/azure-guidance#11]
The current section is a tease because it mentions a feature but provides no implementation details or guidance. Also, the expect header is only related to sending data to the server, not receiving it.

If you keep this section I would suggest mentioning the following
1) .net clients have this setting enabled by default
2) It will cause 2 round trips for every POST/PUT request.
3) Response to the 100 expect is handled transparently by http.sys, so it needs to be explained how to configure the allowed size for a particular host and clarified that it will apply to every request.

**Comment by JohnPWSharp** [comment]
This material will be updated as suggested

**Comment by bennage** [comment]
@JohnPWSharp can update the status of this?

**Comment by JohnPWSharp** [comment]
This issue has been addressed. The published version already includes the changes.

**Comment by JohnPWSharp** [comment]
This is complete, but I don’t have the rights to update the status.
