### ISSUE TITLE
Guidance on Persistent HTTP Connections is confusing

### ISSUE THREAD

**Issue by darrelmiller** [mspnp/azure-guidance#12]
Since the introduction of HTTP/1.1 in 1999 persistent HTTP connections have been the default.  There is no need for clients to send keep-alive headers unless a client is talking to a HTTP/1.0 server.  I'm assuming every Azure based HTTP server is capable of HTTP/1.1.  
My research has found that the only place HTTP/1.0 is still used is from proxy/caching servers to origin servers.  If a developer is using a client that is behind a proxy that talks HTTP/1.0 to the origin server then having the client send keep-alive will have no benefit because connection values are by-hop anyway, so it will have zero impact on the way the proxy server makes the request.

RFC 7230 even goes as far as to warn against using Keep-Alive https://tools.ietf.org/html/rfc7230#appendix-A.1.2
 
This section should talk about the use of the explicit Connection:close header to override the default behaviour.  e.g. If a mobile client makes a single request once an hour to poll for updates, then it should probably issue connection: close so that the connection is immediately closed, potentially saving battery life of the device.
Or on the server side, if a server is handling a _very_ large number of clients that regularly only issue a single request then it may chose to return connection: close to save server resources.

**Comment by JohnPWSharp** [comment]
This section will be updated accordingly.

**Comment by bennage** [comment]
@JohnPWSharp can update the status of this? @dragon119 and I think that you already took care of this.

**Comment by JohnPWSharp** [comment]
@bennage, @dragon119 This issue has been addressed. The published version already includes the changes.

**Comment by JohnPWSharp** [comment]
This has been completed, but I don’t have the necessary rights to update the status.
