### ISSUE TITLE
Discuss Topics Surrounding Multitenancy 

### ISSUE THREAD

**Issue by enghch** [mspnp/azure-guidance#13]
1) Multitenancy in general
2) Rate limiting (throttling)
3) Generating and managing and securing API keys for tenants
4) Data modelling many-to-many relationships on a large scale
     (e.g. millions of users related to millions of subscriptions related to millions of resources)
5) DocumentDB
6) Azure Key Vault
7) How to manage scenarios where some of your users have thousands of users of their own, others just a few.

**Comment by dragon119** [comment]
Guidance for multi-tenant services is in our backlog. Also this article is 2.5 year old but most of the concepts in it are still valid.
https://msdn.microsoft.com/en-us/library/ff966499.aspx

**Comment by mj1856** [comment]
Also to consider: [Azure SQL Database Elastic Scale](http://azure.microsoft.com/en-us/documentation/articles/sql-database-elastic-scale-introduction/).

[More documentation here](http://azure.microsoft.com/en-us/documentation/articles/sql-database-elastic-scale-documentation-map/).

**Comment by tugberkugurlu** [comment]
Also, is it possible to cover tenant pricing strategies under this umbrella? I am mostly after the recommended way around reflecting the pay as you go pricing to multitenant application customers.

**Comment by dragon119** [comment]
Good point! 
'Financial goals and billing subscribers' section in this page has discussion around billing, pros/cons of fixed fee and pay-as-you-go pricing model.
https://msdn.microsoft.com/en-us/library/jj856952.aspx#sec24

**Comment by dragon119** [comment]
We'll consider it in our next round of guidance.

**Comment by enghch** [comment]
Thanks! Can't wait to see what you guys come up with! This has been great so far and very helpful.
