### ISSUE TITLE
There is guide to connect Azure AD?

### ISSUE THREAD

**Issue by saramgsilva** [mspnp/azure-guidance#15]
Hello guy,

I need to a guide to connect a Cloud Service to Azure AD, but I think this guide does not support that, right?

Thanks
Sara Silva

**Comment by dragon119** [comment]
It's in our backlog. Stay tuned.

**Comment by mj1856** [comment]
@saramgsilva  - Does [this document](https://msdn.microsoft.com/library/azure/dn499820) address the scenario you are interested in?

**Comment by saramgsilva** [comment]
I will see, I did not found that page. Thanks
