### ISSUE TITLE
Application Configuration Management

### ISSUE THREAD

**Issue by juice4145** [mspnp/azure-guidance#17]
Hi,
One thing that seems missing is guidance on configuration management which is a big challenge and cause of incidents. Configuration Management from a standpoint of best practices for managing in Azure the values an application should have in which environment (dev environment settings versus production environment) or region specific values (North America versus Asia), how to update a setting's value and have it applied everywhere versus one environment or region. I'm thinking ways to manage them similar to systems like Puppet's Hiera or Netflix's Archaius.  An example might be configuring throttling or retry logic depending upon what region and the number of resources in that region. Or a data provider that is different in the US versus India.

**Comment by dragon119** [comment]
Thank you for your input! Guidance for configuration is in our backlog. Here's my quick thoughts regarding your points. This design pattern addresses your concern about update settings and have it applied everywhere.
https://msdn.microsoft.com/en-us/library/dn589803.aspx

Environment (local vs. cloud) specific settings is supported by the built-in configuration feature.
https://msdn.microsoft.com/en-us/library/azure/hh369934.aspx

**Comment by juice4145** [comment]
Great, thanks for the update and pointers!
