### ISSUE TITLE
Organization of documents

### ISSUE THREAD

**Issue by mj1856** [mspnp/azure-guidance#2]
IMHO, the size of the guidance documents are way too long.  Markdown documents shouldn't be more than a page or two of content.

It would make more sense to have a folder for each set of guidance, each folder starting with an index document, and then smaller chapter documents in the same folder. Each index document should have a table of contents, with links to each chapter, and the chapters should be numbered.

**Comment by StevePxxxx** [comment]
I like a complete document document with highlights at the fore and detail behind, not enough information renders it less effective in meeting the readers needs.

I disagree on folders and index documents, leads to documents lost in layers of folders and index pages, it's 'old-school' and leads to confusion for those seeking a particular piece of content, also those searching has to know the top level folder that would be the 'category' (or similar such obscure title).  

Flat stores or minimal structure I prefer, I then utilise search functions to find the document and/or specific content I want, so search function is the answer, not structure and index, to me.

**Comment by dragon119** [comment]
Thank you for sharing your idea! We're experimenting ToC like this. https://github.com/mspnp/azure-guidance/blob/master/API-Design.md  Does this help you search for topics?
