### ISSUE TITLE
Document DB partitioning section needs update to reflect removal of CUs, also some formatting issues

### ISSUE THREAD

**Issue by LinusLeonard** [mspnp/azure-guidance#21]
https://github.com/mspnp/azure-guidance/blob/master/Data-partitioning.md needs to be revised with regards to Document DB. It needs to reflect the fact that capacity units have been removed. Also, the heading is not formatted properly (it's accidentally part of a bullet list).

**Comment by dragon119** [comment]
Thank you for your feedback. We have revised the section of DocumentDB.
