### ISSUE TITLE
use IHttpActionResult 

### ISSUE THREAD

**Issue by bennage** [mspnp/azure-guidance#3]
There are good arguements for standardizing on `IHttpActionResult` raised by @darrelmiller.
See the discussion beginning here:
https://gitter.im/mspnp/azure-guidance?at=553035100e3138bb6be858e5

https://msdn.microsoft.com/en-us/library/system.web.http.ihttpactionresult%28v=vs.118%29.aspx
http://www.bizcoder.com/composing-api-responses-for-maximum-reuse

**Comment by JohnPWSharp** [comment]
The code samples will be updated in the near future
