### ISSUE TITLE
Broken link in Scalability-checklist.md

### ISSUE THREAD

**Issue by snobu** [mspnp/azure-guidance#45]
In https://github.com/mspnp/azure-guidance/blob/master/Scalability-checklist.md

> Carry out performance profiling and load testing during development, as part of test routines, and before final release to ensure the application performs and scales as required. This testing should occur on the same type of hardware as the production platform, and with the same types and quantities of data and user load as it will encounter in production. For more information, see the page __Testing the Performance of a Cloud Service__ on the Microsoft website.

__Testing the Performance of a Cloud Service__ links to https://msdn.microsoft.com/library/azure/hh369930.aspx which doesn't seem to be there anymore.

**Comment by mekoda** [comment]
Thanks! 

It's now referenced in PR #46.

**Comment by bennage** [comment]
I closed the PR in this repo and opened one in the official content repo:
Azure/azure-content#392
