### ISSUE TITLE
Azure SQL DBs supports distributed transactions

### ISSUE THREAD

**Issue by itaysk** [mspnp/azure-guidance#47]
Hi (loved this article BTW),
In the RDBMS section, in comparison table, there's a line for "Consistency" that states that for SQL Server, distributed transactions are supported, but for Azure SQL DB it is not. Maybe consider soften the message according to this (distributed transactions between SQL DBs is supported): [https://azure.microsoft.com/en-gb/blog/elastic-database-transactions-with-azure-sql-database/](https://azure.microsoft.com/en-gb/blog/elastic-database-transactions-with-azure-sql-database/)

**Comment by dragon119** [comment]
Thank you for the feedback. We'll incorporate this point shortly.

**Comment by mekoda** [comment]
Thanks! It's fixed in #51.
