### ISSUE TITLE
Azure Data Warehouse size limit

### ISSUE THREAD

**Issue by itaysk** [mspnp/azure-guidance#49]
The comparison table for "PDW" types of databases states that Azure Data Warehouse is limited by 51200GB. But all docs and public statements says it's "Petabyte scale"
For example: [https://azure.microsoft.com/en-gb/pricing/details/sql-data-warehouse/](https://azure.microsoft.com/en-gb/pricing/details/sql-data-warehouse/)

**Comment by bennage** [comment]
Sorry for the embarrassingly long delay. We've passed this along to the appropriate team.
