### ISSUE TITLE
Incorrect statement about HTTP protocol related to response to 201

### ISSUE THREAD

**Issue by darrelmiller** [mspnp/azure-guidance#5]
"according to the HTTP protocol, a POST operation should return status code 201" This is not correct.

The spec says "If one or more resources has been created on the origin server as a result of successfully processing a POST request, the origin server SHOULD send a 201"

The difference is that the spec say "if" a resource has been created.  That is not necessarily the case.

**Comment by JohnPWSharp** [comment]
This sentence occurs within the context of an example showing a POST method that creates a new resource, so I think the sentence is factually correct. However, I have added a "in this case" qualifier to the sentence just to clarify matters.
