### ISSUE TITLE
"POST actions should create new resources without additional side-effects" is poor guidance

### ISSUE THREAD

**Issue by darrelmiller** [mspnp/azure-guidance#6]
There are many examples where creating a single resource, would automatically generate secondary resources.  

e.g. 
- Creating a new user may create a corresponding set of default permission resources.
- Creating a new JobRequest resource may subsequently cause the addition of a RunningJob resource to a ProcessingQueue resource.

The semantics of POST are unbounded by the HTTP specification and are controlled purely by the target resource.  This is done intentionally as a catch-all for implementing functionality that does not fit into the other more precisely defined methods.

**Comment by JohnPWSharp** [comment]
I have amended this bullet point to qualify the action of the POST operation in this example.

**Comment by darrelmiller** [comment]
The updates are a definite improvement.  However, I'm unsure as to why there is guidance against side-effects.

It might be helpful if you could clarify why it is you are trying to constrain the POST method.  A POST request might update an audit trail.  It could update metrics on a dashboard.  Are these what you consider "directly related" resources or are you suggesting that updating resources list that is a bad practice?  Why should a client consuming an API be concerned about that other resources get updated when it performs a POST? 
 
Let me explain the reason for my persistence :-)  I've lived through the "That's not REST" wars which were completely unproductive, and then on the other side being told that REST is full of dogma.  The reality is that the actual constraints of REST all have extremely practical reasons for their existence.  Introducing new guidance that isn't explicit about the net benefits to the system will be adopted blindly by some and outright rejected by others.  Neither of which is ideal.
