### ISSUE TITLE
Add language to FMA paragraph to include Effects analysis

### ISSUE THREAD

**Issue by jwes2** [mspnp/azure-guidance#69]
Recommend changing this working for FMA section:

Existing text:

Perform a failure mode analysis (FMA) for your application. The FMA process identifis what types of failures an application might experience, where these failures will happen, and the best practices for recovery. For more information, see Designing resilient applications for Azure: Failure mode analysis.

New text: (changes **highlighted**)

Perform a failure mode analysis (FMA) for your application. The FMA process **identifies** what types of failures an application might experience, where these failures will happen**, captures the effects and impact of the failures,** and the best practices for recovery. For more information, see Designing resilient applications for Azure: Failure mode analysis.

**Comment by MikeWasson** [comment]
Good suggestion, thanks. (And good catch on the typo 😄 )
