### ISSUE TITLE
FMA document should link to detailed paper on process

### ISSUE THREAD

**Issue by jwes2** [mspnp/azure-guidance#72]
The introduction section of **Designing resilient applications for Azure: Failure mode analysis** is a good overview at a very high level but if people actually want to look at how the process is implemented in detail than the http://aka.ms/resiliency link is a good one to give them detailed guidance on FMA.

This link is also provided in other locations like within **Designing resilient applications for Azure** so it's puzzling why it's not included in this paper.

**Comment by MikeWasson** [comment]
Added link to the PDF
