### ISSUE TITLE
"Considerations for optimizing client-side data access" contains poor guidance

### ISSUE THREAD

**Issue by darrelmiller** [mspnp/azure-guidance#8]
This section should not be recommending developers attempt to implement HTTP caching as part of their client applications.  Clients should enable existing caching solutions like WinInet caching or other alternatives.  Implementing correct HTTP caching is a non-trivial task.

**Comment by JohnPWSharp** [comment]
I am not sure that this section actually recommends to developers that they should implement client-side caching. This material is more about implementing servers that support client-side caching (whether these requests come directly from a client or an intermediate server). This is an important consideration.

**Comment by darrelmiller** [comment]
Re-reading this I see what you mean.  There are a number of uses of "should" that I read as suggesting to the reader that they would be the ones implementing this behaviour.  However, I suspect the word was intended to infer that the behaviour might happen.

e.g. "If the data was changed by another user changed (status code 412) or not found (status code 404) then the cached object should be discarded"  

Interestingly, the HTTP caching spec has nothing to say about how invalidation occurs with non 2XX response codes, so the actual behaviour is completely implementation dependent. https://tools.ietf.org/html/rfc7234#section-4.4
