### ISSUE TITLE
"or it could specify no-cache in which case the data should not be cached" is incorrect

### ISSUE THREAD

**Issue by darrelmiller** [mspnp/azure-guidance#9]
Unfortunately "no-cache" does not mean that data should not be cached.  "no-store" means that data should not be cached.  "no-cache" tells a cache not to serve the cached copy until it has been re-validated.

**Comment by JohnPWSharp** [comment]
I have clarified this in the doc. I have switched to "no-store", but added a note advising readers not to fall into the same trap that I did with "no-cache".
